server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quora
    username: quora_admin
    password: quora_admin

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect